build/exec_heur instance_file=instances_slr/boston424.txt targets_file_name=instances_slr/targets/targets_boston.txt initial_capacities_file_name=instances_slr/status/boston_station_status.json

build/exec_heur instance_file=instances_slr/chicago1679.txt targets_file_name=instances_slr/targets/targets_chicago.txt initial_capacities_file_name=instances_slr/status/chicago_station_status.json

build/exec_heur instance_file=instances_slr/madrid611.txt targets_file_name=instances_slr/targets/targets_madrid.txt initial_capacities_file_name=instances_slr/status/madrid_station_status.json

build/exec_heur instance_file=instances_slr/mexicocity662.txt targets_file_name=instances_slr/targets/targets_mexico.txt initial_capacities_file_name=instances_slr/status/mexico_station_status.json

build/exec_heur instance_file=instances_slr/montreal801.txt targets_file_name=instances_slr/targets/targets_montreal.txt initial_capacities_file_name=instances_slr/status/montreal_station_status.json

build/exec_heur instance_file=instances_slr/newyork2176.txt targets_file_name=instances_slr/targets/targets_newyork.txt initial_capacities_file_name=instances_slr/status/newyork_station_status.json

build/exec_heur instance_file=instances_slr/sanfrancisco555.txt targets_file_name=instances_slr/targets/targets_sanfrancisco.txt initial_capacities_file_name=instances_slr/status/sanfrancisco_station_status.json

build/exec_heur instance_file=instances_slr/toronto792.txt targets_file_name=instances_slr/targets/targets_toronto.txt initial_capacities_file_name=instances_slr/status/toronto_station_status.json

build/exec_heur instance_file=instances_slr/washington739.txt targets_file_name=instances_slr/targets/targets_washington.txt initial_capacities_file_name=instances_slr/status/washington_station_status.json

